[project]
name = "iphone-cua"
description = "A simulator env to train agents that can use iphones."
tags = ["placeholder-tag", "train", "eval"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.4",
    "paramiko"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
